[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
FUNC_BIN_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/func/bin"
BINARY_NAME = "wfinfo"
PUBLISH_CARGO_TARGET_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/publish"
PUBLISH_BUILD_TARGET = "x86_64-unknown-linux-musl"

[config]
default_to_workspace = false

[tasks.publish-flow]
dependencies = [
    "wait",
    "publish-build-flow",
    "pre-publish",
    "publish",
    "post-publish"
]

[tasks.publish-build-flow]
category = "Publish"
dependencies = ["pre-publish-build", "publish-build", "post-publish-build"]

[tasks.pre-publish-build]
category = "Publish"

[tasks.publish-build]
category = "Publish"
dependencies = ["pre-publish-build"]
env = { CARGO_TARGET_DIR = "${PUBLISH_CARGO_TARGET_DIR}" }
description = "Builds the application"
command = "cargo"
args = ["build", "--release", "--target", "${PUBLISH_BUILD_TARGET}"]

[tasks.post-publish-build]
category = "Publish"
dependencies = ["publish-build"]
env = { OUT_PATH = "${PUBLISH_CARGO_TARGET_DIR}/${PUBLISH_BUILD_TARGET}/release/${BINARY_NAME}" }
script = '''
mkdir -p "$FUNC_BIN_DIR"
cp "$OUT_PATH" "$FUNC_BIN_DIR/handler"
'''

[tasks.publish]
clear = true
category = "Publish"
dependencies = ["pre-publish"]
env_files = [".env"]
script = '''
cd func
func azure functionapp publish $FUNCTION_APP_NAME
'''

[tasks.build]
args = ["build"]

[tasks.post-build]
script = '''
OUT_PATH="${CARGO_MAKE_WORKING_DIRECTORY}/target/cargo/debug/$BINARY_NAME"
FUNC_BIN_DIR="${CARGO_MAKE_WORKING_DIRECTORY}/func/bin"

mkdir -p "$FUNC_BIN_DIR"
cp "$OUT_PATH" "$FUNC_BIN_DIR/handler"
'''

[tasks.test]
args = ["test"]

[tasks.run]
env_files = [".env"]
category = "Run"
# dependencies = ["dev-test-flow"]
dependencies = ["pre-build", "build", "post-build"]
script = '''
cd func
func start --port 7071
'''
