# Based on https://github.com/bevyengine/bevy/blob/master/.cargo/config_fast_builds

[build]
target-dir = "target/cargo"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
incremental = false

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]

# NOTE: you must manually install https://github.com/michaeleisel/zld on mac. you can easily do this with the "brew" package manager:
# `brew install michaeleisel/zld/zld`
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=off"]
