name: Deploy infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The environment to deploy to.
        required: true

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: read

jobs:
  arm:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          deploymentName: GitHub-${{ github.run_id }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          template: ./resources/arm/wf-price-butler.json
          parameters: >-
            envName=${{ github.event.inputs.environment }}
            appId=${{ secrets.APP_ID }}
            clientId=${{ secrets.CLIENT_ID }}
            clientSecret=${{ secrets.CLIENT_SECRET }}
            discordPublicKey=${{ secrets.DISCORD_PUBLIC_KEY }}
