name: Deploy (dev)

on:
  push:
    branches: [dev, deploy-dev]

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_ARGS: --release --verbose

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install musl-gcc and dependencies
        run: |-
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y musl-tools
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          components: rustfmt, clippy
          override: true
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v1
        with:
          sharedKey: dev-build
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ env.CARGO_BUILD_ARGS }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service: [dispatcher, processor]
        include:
          - service: dispatcher
            package: wfinfo_dispatcher
            fa_name_var: DISPATCHER_FA_NAME
            fa_publish_profile_var: DISPATCHER_FA_PUBLISH_PROFILE
          - service: processor
            package: wfinfo_processor
            fa_name_var: PROCESSOR_FA_NAME
            fa_publish_profile_var: PROCESSOR_FA_PUBLISH_PROFILE
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          components: rustfmt, clippy
          override: true
      - name: Restore build cache
        uses: Swatinem/rust-cache@v1
        with:
          sharedKey: dev-build
      - name: Ensure project is built
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p ${{ matrix.package }} ${{ env.CARGO_BUILD_ARGS }}
      - name: Prepare ${{ matrix.service }}
        run: |-
          ls -al
          cd services/${{ matrix.package }}
          ls -al
          ls -al ./func
          mkdir -p ./func/bin
          ls -al ./target
          ls -al ./target/cargo
          ls -al ./target/cargo/x86_64-unknown-linux-musl/
          ls -al ./target/cargo/x86_64-unknown-linux-musl/release
          cp ./target/cargo/x86_64-unknown-linux-musl/release/wfinfo_${{ matrix.service }} ./func/bin/handler
      - name: Deploy ${{ matrix.service }}
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets[matrix.fa_name_var] }}
          package: services/${{ matrix.package }}/func
          publish-profile: ${{ secrets[matrix.fa_publish_profile_var] }}
