name: Deploy (dev)

on:
  push:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets:
      AZURE_RBAC_CREDENTIALS: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
      DISPATCHER_FA_NAME: ${{ secrets.DISPATCHER_FA_NAME }}
      PROCESSOR_FA_NAME: ${{ secrets.PROCESSOR_FA_NAME }}
