name: Deploy (dev)

on:
  push:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DISPATCHER_FA_NAME: ${{ secrets.DISPATCHER_FA_NAME }}
      PROCESSOR_FA_NAME: ${{ secrets.PROCESSOR_FA_NAME }}
