name: Deploy (prod)

on:
  push:
    branches: [prod]

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_ARGS: --release --verbose

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
    secrets:
      AZURE_RBAC_CREDENTIALS: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
      DISPATCHER_FA_NAME: ${{ secrets.DISPATCHER_FA_NAME }}
      PROCESSOR_FA_NAME: ${{ secrets.PROCESSOR_FA_NAME }}
