name: Deploy (prod)

on:
  push:
    branches: [prod]

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_ARGS: --release --verbose

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
